apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    name: vote
    version: v1 
    type: front-end
spec:
  containers:
  - name: vote
    image: pragra/vote:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
