apiVersion: v1
kind: ReplicationController
metadata:
  name: voters
spec:
  replicas: 3
  selector:
    app: voters
  template:
    metadata:
      name: voters
      labels:
        app: voters
    spec:
      containers:
        - name: voters
          image: pragra/vote:v1
          ports:
            - containerPort: 80
