apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vote
  labels:
    app: vote
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        tier: frontend
        app: vote
    spec:
      containers:
      - name: vote
        image: pragra/vote:v1