apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vote-green
  labels:
    name:  vote-green
spec:
  replicas: 4
  strategy:
    type: Recreate
    # rollingUpdate:
    #   maxSurge: 1
    #   maxUnavailable: 1
  selector:
    matchLabels:
      app: vote-green
  revisionHistoryLimit: 4
  template:
    metadata:
      labels:
        name:  vote-green
        app: vote-green
    spec:
      containers:
      - image:  pragra/vote:v2
        name:  vote-green
        envFrom:
          - configMapRef:
              name: vote
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort:  80
          name:  main-port
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
